2020-01-20 15:21:06,664 ERROR: Exception on / [GET] [in /Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/app/main/routes.py", line 17, in home
    return render_template('main.html')
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/app/templates/main.html", line 1, in top-level template code
    {% extends 'welcome.html' %}
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: welcome.html
2020-01-20 15:21:08,136 ERROR: Exception on / [GET] [in /Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/app/main/routes.py", line 17, in home
    return render_template('main.html')
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/app/templates/main.html", line 1, in top-level template code
    {% extends 'welcome.html' %}
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/danielvaroli/Desktop/personal_website/danielvaroli/venv/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: welcome.html
2020-01-20 15:21:46,223 INFO: Workout App startup [in /Users/danielvaroli/Desktop/personal_website/danielvaroli/app/__init__.py:52]
2020-01-21 15:07:31,744 INFO: Workout App startup [in /Users/danielvaroli/Desktop/personal_website/danielvaroli/app/__init__.py:69]
2020-01-21 15:13:58,229 INFO: Workout App startup [in /Users/danielvaroli/Desktop/personal_website/danielvaroli/app/__init__.py:69]
2020-01-28 20:11:04,896 INFO: Workout App startup [in /Users/danielvaroli/Desktop/personal_website/danielvaroli/app/__init__.py:73]
2020-01-28 20:29:44,762 INFO: Workout App startup [in /Users/danielvaroli/Desktop/personal_website/danielvaroli/app/__init__.py:73]
2020-01-29 19:13:17,624 INFO: Workout App startup [in /Users/danielvaroli/Desktop/personal_website/danielvaroli/app/__init__.py:73]
2020-01-29 19:30:03,873 INFO: Workout App startup [in /Users/danielvaroli/Desktop/personal_website/danielvaroli/app/__init__.py:73]
2020-01-29 19:36:18,408 INFO: Workout App startup [in /Users/danielvaroli/Desktop/personal_website/danielvaroli/app/__init__.py:73]
2020-01-30 10:12:54,310 INFO: Workout App startup [in /Users/danielvaroli/Desktop/personal_website/danielvaroli/app/__init__.py:73]
